# Generated by Django 5.1.1 on 2024-09-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_logged_in',
        ),
    ]
