# Generated by Django 5.1.1 on 2024-09-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_event_total_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_status',
        ),
    ]
